In [2]:
import os
import pandas as pd
import numpy as py

In [43]:
def deleteTargetRow(df, target):
    """
    删除 DataFrame 中包含指定字符串的行

    Args:
    df: 输入的 DataFrame
    target_string: 要查找的字符串

    Returns:
    删除指定行后的 DataFrame
    """
    mask = ~df.apply(lambda row: row.astype(str).str.contains(target))
    dfFilterd = df[mask]
    return dfFilterd

In [39]:
fileDir = os.path.join(os.path.abspath('.'), '数据')
dataMerge = pd.DataFrame()
for file in os.listdir(fileDir):
    print(file)
    filePath = os.path.join(fileDir, file)
    data = pd.read_csv(filePath, sep=',', encoding='GB18030')
    dataMerge = pd.concat([dataMerge, data])
dataMerge.head()

Sub_3180103611_周家瑞_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3210101419_罗海骁_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3210104642_刘一尘_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220100431_周俊毅_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220100491_潘依缕_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220100496_林子惠_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220100593_徐嘉晟_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220100629_张清昊_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220100633_张嘉凯_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220100660_殷梓文_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220100740_秦翊嘉_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220100776_熊天宇_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220100803_朱航远_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220101015_李烁安_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220101035_杨涵宇_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220101528_罗兴春_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220101542_杨憬怡_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220101670_何雯琦_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220101675_崔好_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220101710_汤朱灿_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220101887_黄品嘉_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220102429_倪燕_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220102692_毛沛炫_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220102749_雷文青_视觉搜索不对称实验_DATA_SearchMerge_AP.csv
Sub_3220103737_张斐煜_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220103772_叶雪莹_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220104451_李木子_视觉搜索不对称实验_DATA_SearchMerge_PA.csv
Sub_3220104981_张琳淼_视觉搜索不对称实验_DATA_SearchMerge_PA.csv

,SubjectAge,SetSize,DistractorCircles,DistractorTriangles,ReactionTime,RepeatedReactionTime,RepeatedTimes,Unnamed: 21
count,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,0.0
mean,20.357143,9.523810,4.511905,4.511905,593.503827,593.503827,0.047088,NaN
std,0.895045,2.888868,4.034278,4.034278,176.599805,176.599805,0.223557,NaN
min,19.000000,4.000000,0.000000,0.000000,253.000000,253.000000,0.000000,NaN
25%,20.000000,8.000000,0.750000,0.750000,481.750000,481.750000,0.000000,NaN
50%,20.000000,12.000000,4.000000,4.000000,556.000000,556.000000,0.000000,NaN
75%,21.000000,12.000000,8.000000,8.000000,657.000000,657.000000,0.000000,NaN
max,24.000000,12.000000,12.000000,12.000000,2478.000000,2478.000000,3.000000,NaN

In [49]:
dataMergeFiltered = deleteTargetRow(dataMerge, target='Data Merge Time')
resultPath = os.path.join(os.path.abspath('.'), 'dataMergeFiltered.xlsx')
dataMergeFiltered.to_excel(resultPath,index=False)